version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=group12
    ports:
      - 3312:3306
    volumes:
      - db-data:/var/lib/mysql
  app:
    image: boniface09887/springboottaxapp:v1.0.3
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/group12
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pass123
volumes:
  db-data: