version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=group12
    ports:
      - 3312:3306
    volumes:
      - db-data:/var/lib/mysql
  app:
    build: ./
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=pass123
      - DATABASE_NAME=mysql
      - DATABASE_PORT=3312
volumes:
  db-data: